name: finance_app
description: A Flutter project to track my finances.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  provider: ^6.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/1024.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#190033"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/1024.png
  
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-regular.ttf
          weight: 400
        - asset: assets/fonts/quicksand-medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand-bold.ttf
          weight: 700
        - asset: assets/fonts/quicksand-light.ttf
          weight: 300

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-regular.ttf
          weight: 400
        - asset: assets/fonts/poppins-medium.ttf
          weight: 500
        - asset: assets/fonts/poppins-bold.ttf
          weight: 700
        - asset: assets/fonts/poppins-light.ttf
          weight: 300
